package Coding;

import Audio_Steganography.Decode_Audio;
import Audio_Steganography.Encode_Audio;
import ImageSteganography.Decryption;
import ImageSteganography.Encryption;
//import TextSteganography.Text_Decryption;
//import TextSteganography.Text_Encryption;
import java.awt.Color;
import java.awt.Dimension;
import java.net.MalformedURLException;
import java.net.URL;
import javax.swing.ImageIcon;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.util.Random;

/**
 *
 * @author Nurul Jannah binti Shahrol Nizam
 */
public class HomePage extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    public HomePage() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        jPanel1 = new javax.swing.JPanel();
        jButtonDecodeAudio = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButtonEncodeAudio = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();

        this.setTitle("Steganography");
        this.setResizable(false);
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
  Random rand = new Random();
        int red = rand.nextInt(256);     // Random value between 0-255
        int green = rand.nextInt(256);   // Random value between 0-255
        int blue = rand.nextInt(256);    
        jPanel1.setBackground(new java.awt.Color(red, green, blue));
        
        jButtonDecodeAudio.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jButtonDecodeAudio.setText("Decode Audio");
        jButtonDecodeAudio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonDecodeAudio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDecodeAudioActionPerformed(evt);
                        }

            private void jButtonDecodeAudioActionPerformed(ActionEvent evt) {
            }
});
//        jPanel2.setBackground(new java.awt.Color(160, 0, 0));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.WHITE, java.awt.Color.lightGray));
         rand = new Random();
         red = rand.nextInt(100, 256);     // Random value between 0-255
         green = rand.nextInt(100,256);   // Random value between 0-255
         blue = rand.nextInt(100, 256);    // Random value between 0-255

        jPanel2.setForeground(new Color(red, green, blue));
//        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

//        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
//        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
//        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
//        jLabel1.setText("SteganoGraphy");
        try {
            URL imageUrl = new URL("https://eregister.kptm.edu.my/img/KPTM-MARA-UPTM.png");
            ImageIcon imageIcon = new ImageIcon(imageUrl);

// Hardcoded dimensions
            int hardcodedWidth = 800; // Example value, set as you need
            int hardcodedHeight = 200; // Example value, set as you need

// Resize the ImageIcon
            Image image = imageIcon.getImage();
            Image newImage = image.getScaledInstance(hardcodedWidth, hardcodedHeight, Image.SCALE_SMOOTH);
            imageIcon = new ImageIcon(newImage);

            jLabel1.setIcon(imageIcon); // Set the resized image as the icon for the jLabel1.
            jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER); // Center the image
            jLabel1.setText(""); // Remove the text from the jLabel1.

        } catch (Exception e) {
            e.printStackTrace();
            // Handle the exception, perhaps show a default image or an error message
        }

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
        );

//        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/programer.jpg"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel2MouseEntered(evt);
            }
        });
   rand = new Random();
         red = rand.nextInt(150, 256);     // Random value between 0-255
         green = rand.nextInt(150, 256);   // Random value between 0-255
         blue = rand.nextInt(150,256);    
        jPanel3.setBackground(new java.awt.Color(red, green, blue));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("By Nurul Jannah binti Shahrol Nizam");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
        );
        jButton5.setFont(new java.awt.Font("Calibri", 1, 36));
        jButton5.setForeground(new java.awt.Color(32, 32, 32));
        jButton5.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        try {
            URL imageUrl = new URL("https://i.imgur.com/9oM42zQ.png");
            ImageIcon imageIcon = new ImageIcon(imageUrl);

            // Get the width and height of the button
            jButton5.setPreferredSize(new Dimension(100, 50));  // example dimensions

            int buttonWidth = jButton5.getWidth();
            int buttonHeight = jButton5.getHeight();

            // Resize the image to fit the button
            Image img = imageIcon.getImage().getScaledInstance(150, 50, Image.SCALE_SMOOTH);
            imageIcon = new ImageIcon(img);

            jButton5.setIcon(imageIcon);  // Set the resized image as the icon for the button.
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }

        jButton5.setText("");  // Remove the text from the button.
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton5MouseEntered(evt);
            }
        });
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("Calibri", 1, 36));
        jButton6.setForeground(new java.awt.Color(23, 23, 23));
        jButton6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
//        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
//            public void mouseEntered(java.awt.event.MouseEvent evt) {
//                jButton6MouseEntered(evt);
//            }
//        });
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

// Setting the image for jButton6 (Decode Image button)
        try {
            URL imageUrl = new URL("https://i.imgur.com/O42vlxk.png");
            ImageIcon imageIcon = new ImageIcon(imageUrl);

            // Get the width and height of the button
            jButton6.setPreferredSize(new Dimension(100, 50));  // example dimensions

            int buttonWidth = jButton6.getWidth();
            int buttonHeight = jButton6.getHeight();

            // Resize the image to fit the button
            Image img = imageIcon.getImage().getScaledInstance(150, 50, Image.SCALE_SMOOTH);
            imageIcon = new ImageIcon(img);

            jButton6.setIcon(imageIcon);  // Set the resized image as the icon for the button.
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }

//        try {
//            URL imageUrlForButton6 = new URL("https://www.itjobs.pt/empresa/decode/logo/social");
//            ImageIcon imageIconForButton6 = new ImageIcon(imageUrlForButton6);
//
//            // Get the width and height of the button
//            int buttonWidth = jButton6.getWidth();
//            int buttonHeight = jButton6.getHeight();
//
//            // Resize the image to fit the button
//            Image img = imageIconForButton6.getImage().getScaledInstance(buttonWidth, buttonHeight, Image.SCALE_SMOOTH);
//            imageIconForButton6 = new ImageIcon(img);
//
//            // Set the resized image as the icon for the button
//            jButton6.setIcon(imageIconForButton6);
//
//        } catch (MalformedURLException e) {
//            e.printStackTrace();
//        }
        jButton6.setText("");  // Remove the text from the button.

        jButton6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton6MouseEntered(evt);
            }
        });
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

//        jButtonEncodeAudio.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
//        jButtonEncodeAudio.setText("Encode Audio");
//        jButtonEncodeAudio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
//        jButtonEncodeAudio.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                jButtonEncodeAudioActionPerformed(evt);
//            }
//        });
//
//        jButton7.setFont(new java.awt.Font("Algerian", 1, 30)); // NOI18N
//        jButton7.setText("Encode Text");
//        jButton7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
//        jButton7.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                jButton7ActionPerformed(evt);
//            }
//        });
        try {
            URL imageUrl = new URL("https://i.imgur.com/lpLGbCN.png");
            ImageIcon imageIcon = new ImageIcon(imageUrl);

            // Get the width and height of the button
            jButton8.setPreferredSize(new Dimension(100, 50));  // example dimensions

            int buttonWidth = jButton8.getWidth();
            int buttonHeight = jButton8.getHeight();

            // Resize the image to fit the button
            Image img = imageIcon.getImage().getScaledInstance(150, 50, Image.SCALE_SMOOTH);
            imageIcon = new ImageIcon(img);

            jButton8.setIcon(imageIcon);  // Set the resized image as the icon for the button.
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        jButton8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(200, 200, 200) // This gap can be adjusted as per the design requirement
                                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(200, 200, 200)) // This gap can be adjusted as per the design requirement
        );

        // Vertical layout
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50) // This gap can be adjusted as per the design requirement
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 150, Short.MAX_VALUE) // This gap can be adjusted as per the design requirement
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseEntered

    }//GEN-LAST:event_jLabel2MouseEntered

    private void jButton5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseEntered

//        jButton2.setBackground(Color.lightGray);
    }//GEN-LAST:event_jButton5MouseEntered

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        Encryption a = new Encryption();

        a.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseEntered

        jButtonEncodeAudio.setBackground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_jButton6MouseEntered

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        Decryption a = new Decryption();

        a.setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

//    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
//        Text_Encryption te = new Text_Encryption();
//        te.setVisible(true);
//        te.setLocationRelativeTo(null);
//    }//GEN-LAST:event_jButton7ActionPerformed
//    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
//        
//        Text_Decryption td = new Text_Decryption();
//        td.setVisible(true);
//        td.setLocationRelativeTo(null);
//    }//GEN-LAST:event_jButton2ActionPerformed
    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        SendEmail se = new SendEmail();
        se.setVisible(true);
        se.setLocationRelativeTo(null);
    }//GEN-LAST:event_jButton8ActionPerformed

//    private void jButtonEncodeAudioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEncodeAudioActionPerformed
//        Encode_Audio ea = new Encode_Audio();
//        ea.setVisible(true);
//        ea.setLocationRelativeTo(null);
//    }//GEN-LAST:event_jButtonEncodeAudioActionPerformed
//    private void jButtonDecodeAudioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDecodeAudioActionPerformed
//        Decode_Audio da = new Decode_Audio();
//        da.setVisible(true);
//        da.setLocationRelativeTo(null);
//    }//GEN-LAST:event_jButtonDecodeAudioActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButtonDecodeAudio;
    private javax.swing.JButton jButtonEncodeAudio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
